links:
- text: 'top'
  href: '/?page=top'
- text: 'resent posts'
  href: '/?post'
- text: '外部サイト'
  href: './'
  sublinks:
  - text: 'ソースコード'
    href: 'https://github.com/tychy/bashcms'
  - text: 'Github Profile'
    href: 'https://github.com/tychy'
